In [8]:
import pandas as pd
import numpy as np
import os

In [7]:
# Look at headings of the dataset
df = pd.read_csv("12/01.csv")
df.columns

/var/folders/gt/v2b3tmpx1ylfjtn6js5pvrb00000gn/T/ipykernel_88438/3765449228.py:2: DtypeWarning: Columns (22,40) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("12/01.csv")

Index(['CARRIER', 'CARRIER_CD_ICAO', 'FLTNO', 'FLTSUFFX', 'DEPAPT',
       'DEP_PORT_CD_ICAO', 'DEPTERM', 'DEPCITY', 'DEPCTRY', 'ARRAPT',
       'ARR_PORT_CD_ICAO', 'ARRTERM', 'ARRCITY', 'ARRCTRY', 'DEPTIM',
       'SCHEDULED_DEPARTURE_TIME_UTC', 'SCHEDULED_DEPARTURE_DATE_TIME_LOCAL',
       'SCHEDULED_DEPARTURE_DATE_TIME_UTC', 'ARRTIM',
       'SCHEDULED_ARRIVAL_TIME_UTC', 'SCHEDULED_ARRIVAL_DATE_TIME_LOCAL',
       'SCHEDULED_ARRIVAL_DATE_TIME_UTC', 'ARRDAY', 'ELPTIM', 'FLIGHT_DATE',
       'SCHEDULED_DEPARTURE_DATE_UTC', 'SCHEDULED_ARRIVAL_DATE_LOCAL',
       'SCHEDULED_ARRIVAL_DATE_UTC', 'STOPS', 'GENACFT', 'INPACFT',
       'EQUIPMENT_CD_ICAO', 'ACFTCHANGE', 'SERVICE', 'PX', 'MEALS', 'FRTCLASS',
       'TONS', 'COMM10_50', 'OPERATING', 'GHOST', 'DUPCARFL', 'SAD',
       'SAD_NAME', 'ACFT_OWNER', 'RESTRICT', 'DOMINT', 'ROUTING', 'LONGEST',
       'INTAPT', 'DISTANCE', 'GOVT_APP', 'INFLTSERVICE', 'SECUREFLT',
       'FIRST_CLASS_SEATS', 'BUSINESS_CLASS_SEATS',
       'PREMIUM_ECONOMY_CLASS_SEATS', 'ECONOMY_PLUS_CLASS_SEATS',
       'ECONOMY_CLASS_SEATS', 'TOTAL_SEATS', 'OAG_SCHEDULE_FINGERPRINT',
       'FILE_DATE'],
      dtype='object')

In [9]:
os.listdir(".")

['training.ipynb',
 'final_merged_data.csv',
 'emissions.csv',
 'emissions_join.py',
 '12',
 'travel-environment']

In [11]:
emissions_df = pd.read_csv("emissions.csv")
emissions_df.columns

/var/folders/gt/v2b3tmpx1ylfjtn6js5pvrb00000gn/T/ipykernel_88438/695183605.py:1: DtypeWarning: Columns (2,3,24) have mixed types. Specify dtype option on import or set low_memory=False.
  emissions_df = pd.read_csv("emissions.csv")

Index(['SCHEDULED_FLIGHT_LEG_PK', 'CARRIER_CODE', 'OUTBOUND_CODE',
       'SERVICE_SUFFIX', 'FLIGHT_NUMBER', 'DEPARTURE_AIRPORT',
       'ARRIVAL_AIRPORT', 'SCHEDULED_DEPARTURE_DATE', 'AIRCRAFT_TYPE', 'SEATS',
       'ESTIMATED_FUEL_BURN_TAXI_OUT_TONNES',
       'ESTIMATED_FUEL_BURN_TAKEOFF_TONNES',
       'ESTIMATED_FUEL_BURN_CLIMBOUT_TONNES',
       'ESTIMATED_FUEL_BURN_CRUISE_TONNES',
       'ESTIMATED_FUEL_BURN_APPROACH_TONNES',
       'ESTIMATED_FUEL_BURN_TAXI_IN_TONNES',
       'ESTIMATED_FUEL_BURN_TOTAL_TONNES', 'ESTIMATED_CO2_TAXI_OUT_TONNES',
       'ESTIMATED_CO2_TAKEOFF_TONNES', 'ESTIMATED_CO2_CLIMBOUT_TONNES',
       'ESTIMATED_CO2_CRUISE_TONNES', 'ESTIMATED_CO2_APPROACH_TONNES',
       'ESTIMATED_CO2_TAXI_IN_TONNES', 'ESTIMATED_CO2_TOTAL_TONNES',
       'MISSING_REFERENCE_FLIGHT_TIMES', 'LOAD_DATE', 'IS_OPERATING'],
      dtype='object')

In [14]:
emissions_df.tail()

,SCHEDULED_FLIGHT_LEG_PK,CARRIER_CODE,OUTBOUND_CODE,SERVICE_SUFFIX,FLIGHT_NUMBER,DEPARTURE_AIRPORT,ARRIVAL_AIRPORT,SCHEDULED_DEPARTURE_DATE,AIRCRAFT_TYPE,SEATS,...,ESTIMATED_CO2_TAXI_OUT_TONNES,ESTIMATED_CO2_TAKEOFF_TONNES,ESTIMATED_CO2_CLIMBOUT_TONNES,ESTIMATED_CO2_CRUISE_TONNES,ESTIMATED_CO2_APPROACH_TONNES,ESTIMATED_CO2_TAXI_IN_TONNES,ESTIMATED_CO2_TOTAL_TONNES,MISSING_REFERENCE_FLIGHT_TIMES,LOAD_DATE,IS_OPERATING
328867,f49b59b6577b132f086cb68c1cd67aefcfebebdc75e358...,ZV,NaN,NaN,420,CZM,CUN,2024-12-22,CNF,12.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,2024-12-05,True
328868,ac75acf7e1b5151c910635a349324680b29aab7cbefb75...,ZV,NaN,NaN,450,CTM,CUN,2024-12-13,CNF,12.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,2024-12-05,True
328869,07977f04339f9b546317ae1d459ec959aadf837df8127b...,ZV,NaN,NaN,451,CUN,CTM,2024-12-31,CNF,12.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,2024-12-05,True
328870,81f2d2d5a14db58e003f06b78e884729b6e708c24a8977...,ZV,NaN,NaN,474,CUN,MID,2024-12-25,CNF,12.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,2024-12-05,True
328871,0a7acd58411f00e3cd837ec502b7b66f01f92eb66c6222...,ZV,NaN,NaN,475,MID,CUN,2024-12-18,CNF,12.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,2024-12-05,True

In [16]:
merged_df = pd.read_csv("final_merged_data.csv")
merged_df.head()

,ESTIMATED_CO2_TOTAL_TONNES,OAG_SCHEDULE_FINGERPRINT,DEPCTRY,ARRCTRY,ELPTIM,STOPS,DISTANCE
0,28.122,c98d6c8913aee5fc4fb818ee30a11c7db21639eb4dfddd...,RU,TR,430,0,1701
1,4.950,8af73edb43487f2281a51b615284351250f0ed54133cb4...,NZ,NF,245,0,678
2,1.430,92f6868b2f19f58c6dbaa2507eccbcaf0a648a9d178624...,NZ,NZ,115,0,269
3,35.642,44ecffd69dde3fdca6969c521084e380e9d654b0616434...,SG,CN,450,0,2019
4,12.384,5d01c781e57279e87d49db1dd780b3cc30906cfd162ebf...,CN,CN,155,0,610

In [19]:
merged_df.shape

(217543, 7)

In [20]:
df.shape

(202126, 62)

In [21]:
# Merge all the 31 days of data in 12 folder and save
all_days_data = []

for day in range(1, 32):  # Days 1 to 31
    filename = f"12/{day:02d}.csv"  # Format as 01.csv, 02.csv, etc.
    if os.path.exists(filename):
        day_df = pd.read_csv(filename)
        all_days_data.append(day_df)
        print(f"Loaded {filename}: {day_df.shape[0]} rows")
    else:
        print(f"File not found: {filename}")

# Concatenate all dataframes
december_merged = pd.concat(all_days_data, ignore_index=True)
print(f"\nTotal merged data shape: {december_merged.shape}")

# Save to CSV
december_merged.to_csv("december_2024_merged.csv", index=False)
print("Saved to december_2024_merged.csv")

december_merged.head()

/var/folders/gt/v2b3tmpx1ylfjtn6js5pvrb00000gn/T/ipykernel_88438/2185328218.py:7: DtypeWarning: Columns (22,40) have mixed types. Specify dtype option on import or set low_memory=False.
  day_df = pd.read_csv(filename)

Loaded 12/01.csv: 202126 rows

/var/folders/gt/v2b3tmpx1ylfjtn6js5pvrb00000gn/T/ipykernel_88438/2185328218.py:7: DtypeWarning: Columns (22,40) have mixed types. Specify dtype option on import or set low_memory=False.
  day_df = pd.read_csv(filename)

Loaded 12/02.csv: 207270 rows

/var/folders/gt/v2b3tmpx1ylfjtn6js5pvrb00000gn/T/ipykernel_88438/2185328218.py:7: DtypeWarning: Columns (22) have mixed types. Specify dtype option on import or set low_memory=False.
  day_df = pd.read_csv(filename)

Loaded 12/03.csv: 195208 rows

/var/folders/gt/v2b3tmpx1ylfjtn6js5pvrb00000gn/T/ipykernel_88438/2185328218.py:7: DtypeWarning: Columns (22,40) have mixed types. Specify dtype option on import or set low_memory=False.
  day_df = pd.read_csv(filename)

Loaded 12/04.csv: 202089 rows

/var/folders/gt/v2b3tmpx1ylfjtn6js5pvrb00000gn/T/ipykernel_88438/2185328218.py:7: DtypeWarning: Columns (22,40) have mixed types. Specify dtype option on import or set low_memory=False.
  day_df = pd.read_csv(filename)

Loaded 12/05.csv: 203114 rows

/var/folders/gt/v2b3tmpx1ylfjtn6js5pvrb00000gn/T/ipykernel_88438/2185328218.py:7: DtypeWarning: Columns (22,40) have mixed types. Specify dtype option on import or set low_memory=False.
  day_df = pd.read_csv(filename)

Loaded 12/06.csv: 211536 rows

/var/folders/gt/v2b3tmpx1ylfjtn6js5pvrb00000gn/T/ipykernel_88438/2185328218.py:7: DtypeWarning: Columns (22,40) have mixed types. Specify dtype option on import or set low_memory=False.
  day_df = pd.read_csv(filename)

Loaded 12/07.csv: 186775 rows

/var/folders/gt/v2b3tmpx1ylfjtn6js5pvrb00000gn/T/ipykernel_88438/2185328218.py:7: DtypeWarning: Columns (22,40) have mixed types. Specify dtype option on import or set low_memory=False.
  day_df = pd.read_csv(filename)

Loaded 12/08.csv: 195595 rows

/var/folders/gt/v2b3tmpx1ylfjtn6js5pvrb00000gn/T/ipykernel_88438/2185328218.py:7: DtypeWarning: Columns (22,40) have mixed types. Specify dtype option on import or set low_memory=False.
  day_df = pd.read_csv(filename)

Loaded 12/09.csv: 208278 rows

/var/folders/gt/v2b3tmpx1ylfjtn6js5pvrb00000gn/T/ipykernel_88438/2185328218.py:7: DtypeWarning: Columns (22,40) have mixed types. Specify dtype option on import or set low_memory=False.
  day_df = pd.read_csv(filename)

Loaded 12/10.csv: 195905 rows

/var/folders/gt/v2b3tmpx1ylfjtn6js5pvrb00000gn/T/ipykernel_88438/2185328218.py:7: DtypeWarning: Columns (22) have mixed types. Specify dtype option on import or set low_memory=False.
  day_df = pd.read_csv(filename)

Loaded 12/11.csv: 207823 rows

/var/folders/gt/v2b3tmpx1ylfjtn6js5pvrb00000gn/T/ipykernel_88438/2185328218.py:7: DtypeWarning: Columns (22,40) have mixed types. Specify dtype option on import or set low_memory=False.
  day_df = pd.read_csv(filename)

Loaded 12/12.csv: 206526 rows

/var/folders/gt/v2b3tmpx1ylfjtn6js5pvrb00000gn/T/ipykernel_88438/2185328218.py:7: DtypeWarning: Columns (22,32,40) have mixed types. Specify dtype option on import or set low_memory=False.
  day_df = pd.read_csv(filename)

Loaded 12/13.csv: 214021 rows

/var/folders/gt/v2b3tmpx1ylfjtn6js5pvrb00000gn/T/ipykernel_88438/2185328218.py:7: DtypeWarning: Columns (22,40) have mixed types. Specify dtype option on import or set low_memory=False.
  day_df = pd.read_csv(filename)

Loaded 12/14.csv: 193586 rows

/var/folders/gt/v2b3tmpx1ylfjtn6js5pvrb00000gn/T/ipykernel_88438/2185328218.py:7: DtypeWarning: Columns (22,40) have mixed types. Specify dtype option on import or set low_memory=False.
  day_df = pd.read_csv(filename)

Loaded 12/15.csv: 195209 rows

/var/folders/gt/v2b3tmpx1ylfjtn6js5pvrb00000gn/T/ipykernel_88438/2185328218.py:7: DtypeWarning: Columns (22,40) have mixed types. Specify dtype option on import or set low_memory=False.
  day_df = pd.read_csv(filename)

Loaded 12/16.csv: 206069 rows

/var/folders/gt/v2b3tmpx1ylfjtn6js5pvrb00000gn/T/ipykernel_88438/2185328218.py:7: DtypeWarning: Columns (22,40) have mixed types. Specify dtype option on import or set low_memory=False.
  day_df = pd.read_csv(filename)

Loaded 12/17.csv: 197633 rows

/var/folders/gt/v2b3tmpx1ylfjtn6js5pvrb00000gn/T/ipykernel_88438/2185328218.py:7: DtypeWarning: Columns (22,40) have mixed types. Specify dtype option on import or set low_memory=False.
  day_df = pd.read_csv(filename)

Loaded 12/18.csv: 207222 rows

/var/folders/gt/v2b3tmpx1ylfjtn6js5pvrb00000gn/T/ipykernel_88438/2185328218.py:7: DtypeWarning: Columns (22,40) have mixed types. Specify dtype option on import or set low_memory=False.
  day_df = pd.read_csv(filename)

Loaded 12/19.csv: 209626 rows

/var/folders/gt/v2b3tmpx1ylfjtn6js5pvrb00000gn/T/ipykernel_88438/2185328218.py:7: DtypeWarning: Columns (22,40) have mixed types. Specify dtype option on import or set low_memory=False.
  day_df = pd.read_csv(filename)

Loaded 12/20.csv: 218323 rows

/var/folders/gt/v2b3tmpx1ylfjtn6js5pvrb00000gn/T/ipykernel_88438/2185328218.py:7: DtypeWarning: Columns (22,40) have mixed types. Specify dtype option on import or set low_memory=False.
  day_df = pd.read_csv(filename)

Loaded 12/21.csv: 198300 rows

/var/folders/gt/v2b3tmpx1ylfjtn6js5pvrb00000gn/T/ipykernel_88438/2185328218.py:7: DtypeWarning: Columns (22,40) have mixed types. Specify dtype option on import or set low_memory=False.
  day_df = pd.read_csv(filename)

Loaded 12/22.csv: 200010 rows

/var/folders/gt/v2b3tmpx1ylfjtn6js5pvrb00000gn/T/ipykernel_88438/2185328218.py:7: DtypeWarning: Columns (22,40) have mixed types. Specify dtype option on import or set low_memory=False.
  day_df = pd.read_csv(filename)

Loaded 12/23.csv: 211804 rows

/var/folders/gt/v2b3tmpx1ylfjtn6js5pvrb00000gn/T/ipykernel_88438/2185328218.py:7: DtypeWarning: Columns (22,40) have mixed types. Specify dtype option on import or set low_memory=False.
  day_df = pd.read_csv(filename)

Loaded 12/24.csv: 195381 rows

/var/folders/gt/v2b3tmpx1ylfjtn6js5pvrb00000gn/T/ipykernel_88438/2185328218.py:7: DtypeWarning: Columns (22,40) have mixed types. Specify dtype option on import or set low_memory=False.
  day_df = pd.read_csv(filename)

Loaded 12/25.csv: 172880 rows

/var/folders/gt/v2b3tmpx1ylfjtn6js5pvrb00000gn/T/ipykernel_88438/2185328218.py:7: DtypeWarning: Columns (22,40) have mixed types. Specify dtype option on import or set low_memory=False.
  day_df = pd.read_csv(filename)

Loaded 12/26.csv: 211574 rows

/var/folders/gt/v2b3tmpx1ylfjtn6js5pvrb00000gn/T/ipykernel_88438/2185328218.py:7: DtypeWarning: Columns (22,40) have mixed types. Specify dtype option on import or set low_memory=False.
  day_df = pd.read_csv(filename)

Loaded 12/27.csv: 214849 rows

/var/folders/gt/v2b3tmpx1ylfjtn6js5pvrb00000gn/T/ipykernel_88438/2185328218.py:7: DtypeWarning: Columns (22,40) have mixed types. Specify dtype option on import or set low_memory=False.
  day_df = pd.read_csv(filename)

Loaded 12/28.csv: 198032 rows

/var/folders/gt/v2b3tmpx1ylfjtn6js5pvrb00000gn/T/ipykernel_88438/2185328218.py:7: DtypeWarning: Columns (22,40) have mixed types. Specify dtype option on import or set low_memory=False.
  day_df = pd.read_csv(filename)

Loaded 12/29.csv: 198778 rows

/var/folders/gt/v2b3tmpx1ylfjtn6js5pvrb00000gn/T/ipykernel_88438/2185328218.py:7: DtypeWarning: Columns (22,40) have mixed types. Specify dtype option on import or set low_memory=False.
  day_df = pd.read_csv(filename)

Loaded 12/30.csv: 212088 rows

/var/folders/gt/v2b3tmpx1ylfjtn6js5pvrb00000gn/T/ipykernel_88438/2185328218.py:7: DtypeWarning: Columns (22,40) have mixed types. Specify dtype option on import or set low_memory=False.
  day_df = pd.read_csv(filename)

Loaded 12/31.csv: 193665 rows

Total merged data shape: (6271295, 62)

Total merged data shape: (6271295, 62)
Saved to december_2024_merged.csv
Saved to december_2024_merged.csv

,CARRIER,CARRIER_CD_ICAO,FLTNO,FLTSUFFX,DEPAPT,DEP_PORT_CD_ICAO,DEPTERM,DEPCITY,DEPCTRY,ARRAPT,...,INFLTSERVICE,SECUREFLT,FIRST_CLASS_SEATS,BUSINESS_CLASS_SEATS,PREMIUM_ECONOMY_CLASS_SEATS,ECONOMY_PLUS_CLASS_SEATS,ECONOMY_CLASS_SEATS,TOTAL_SEATS,OAG_SCHEDULE_FINGERPRINT,FILE_DATE
0,QJ,NaN,65,NaN,YXE,CYXE,NaN,YXE,CA,YYZ,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,e899f7425009a0933354bc7df6f798d67218dfdedd92f3...,2024-11-30
1,QJ,NaN,67,NaN,YWG,CYWG,NaN,YWG,CA,YYZ,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7d2d3b5106fc45bf817e96aec8d7e1eebfeedc049b85f4...,2024-11-30
2,QJ,NaN,75,NaN,YQR,CYQR,NaN,YQR,CA,YUL,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,648e0b2854d94b7c160c4dba927a25d92097a94532d008...,2024-11-30
3,QJ,NaN,77,NaN,YXE,CYXE,NaN,YXE,CA,YUL,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,b990b1706b90db378b62dc816ac1a749fd4e6dfa853580...,2024-11-30
4,QJ,NaN,79,NaN,YWG,CYWG,NaN,YWG,CA,YUL,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,c2cfe978ec3ab22b66522bca3330577f97faf9289bebd5...,2024-11-30

In [22]:
emissions_df.shape

(328872, 27)

In [ ]:
emissions_df.head